e = {
    "social": {
        "discord": "refraction",
        "twitter": "https://twitter.com/RefractionPlays",
        "hypixel": "https://hypixel.net/members/refraction.32759/",
        "youtube": "https://youtube.com/Refraction",
    },
    "skyblock": [
        {
            "catacombs": {
                "archer": 45,
                "mage": 43,
                "berserk": 48,
                "tank": 45,
                "healer": 43,
                "level": 51,
            },
            "skills": {
                "Fishing": 50,
                "Mining": 60,
                "Combat": 60,
                "Foraging": 50,
                "Taming": 51,
                "Enchanting": 60,
                "Alchemy": 50,
                "Carpentry": 50,
                "Runecrafting": 25,
                "Social": 13,
                "avg": "54.56",
                "Farming": 60,
            },
            "mining": {
                "HOTM": 0,
                "gemstonePowder": 6309047,
                "mithrilPowder": 8372343,
                "hotm": 7,
            },
            "slayers": {
                "zombie": 9,
                "spider": 9,
                "wolf": 9,
                "enderman": 9,
                "blaze": 9,
                "vampire": 5,
            },
            "bank": 1000923831,
            "purse": 3629161046,
            "liquid": 4630084877,
            "members": 9,
            "name": "Apple",
            "gameMode": "Normal",
            "networth": 146290098113,
            "unsoulboundNetworth": 145909653669,
            "craftedMinions": 743,
            "bonusMinions": 5,
            "levels": "441.23",
            "minionSlots": 31,
        },
        {
            "catacombs": {
                "archer": 0,
                "mage": 0,
                "berserk": 0,
                "tank": 0,
                "healer": 0,
                "level": 0,
            },
            "skills": {
                "Fishing": 0,
                "Mining": 0,
                "Combat": 0,
                "Foraging": 0,
                "Taming": 0,
                "Enchanting": 0,
                "Alchemy": 0,
                "Carpentry": 0,
                "Runecrafting": 0,
                "Social": 0,
                "avg": 0,
            },
            "mining": {"HOTM": 0, "gemstonePowder": 0, "mithrilPowder": 0},
            "slayers": {
                "zombie": 0,
                "spider": 0,
                "wolf": 0,
                "enderman": 0,
                "blaze": 0,
                "vampire": 0,
            },
            "bank": 0,
            "purse": 1961,
            "liquid": 1961,
            "members": 1,
            "name": "Tomato",
            "gameMode": "bingo",
            "networth": 0,
            "unsoulboundNetworth": 0,
            "craftedMinions": 0,
            "bonusMinions": 0,
            "levels": 0,
            "minionSlots": 5,
        },
        {
            "catacombs": {
                "archer": 0,
                "mage": 0,
                "berserk": 0,
                "tank": 0,
                "healer": 0,
                "level": 0,
            },
            "skills": {
                "Fishing": 0,
                "Mining": 0,
                "Combat": 0,
                "Foraging": 0,
                "Taming": 0,
                "Enchanting": 0,
                "Alchemy": 0,
                "Carpentry": 0,
                "Runecrafting": 0,
                "Social": 0,
                "avg": 0,
            },
            "mining": {"HOTM": 0, "gemstonePowder": 0, "mithrilPowder": 0},
            "slayers": {
                "zombie": 0,
                "spider": 0,
                "wolf": 0,
                "enderman": 0,
                "blaze": 0,
                "vampire": 0,
            },
            "bank": 0,
            "purse": 0,
            "liquid": 0,
            "members": 1,
            "name": "Zucchini",
            "gameMode": "ironman",
            "networth": 0,
            "unsoulboundNetworth": 0,
            "craftedMinions": 0,
            "bonusMinions": 0,
            "levels": 0,
            "minionSlots": 5,
        },
        {
            "catacombs": {
                "archer": 0,
                "mage": 0,
                "berserk": 0,
                "tank": 0,
                "healer": 0,
                "level": 0,
            },
            "skills": {
                "Fishing": 0,
                "Mining": 0,
                "Combat": 0,
                "Foraging": 0,
                "Taming": 0,
                "Enchanting": 0,
                "Alchemy": 0,
                "Carpentry": 0,
                "Runecrafting": 0,
                "Social": 0,
                "avg": 0,
            },
            "mining": {"HOTM": 0, "gemstonePowder": 0, "mithrilPowder": 0},
            "slayers": {
                "zombie": 2,
                "spider": 2,
                "wolf": 3,
                "enderman": 0,
                "blaze": 0,
                "vampire": 0,
            },
            "bank": 0,
            "purse": 21085869,
            "liquid": 21085869,
            "members": 1,
            "name": "Pineapple",
            "gameMode": "Normal",
            "networth": 0,
            "unsoulboundNetworth": 0,
            "craftedMinions": 140,
            "bonusMinions": 0,
            "levels": 0,
            "minionSlots": 12,
        },
        {
            "catacombs": {
                "archer": 0,
                "mage": 0,
                "berserk": 0,
                "tank": 0,
                "healer": 0,
                "level": 0,
            },
            "skills": {
                "Fishing": 0,
                "Mining": 0,
                "Combat": 0,
                "Foraging": 0,
                "Taming": 0,
                "Enchanting": 0,
                "Alchemy": 0,
                "Carpentry": 0,
                "Runecrafting": 0,
                "Social": 0,
                "avg": 0,
            },
            "mining": {"HOTM": 0, "gemstonePowder": 0, "mithrilPowder": 0},
            "slayers": {
                "zombie": 3,
                "spider": 1,
                "wolf": 0,
                "enderman": 0,
                "blaze": 0,
                "vampire": 0,
            },
            "bank": 0,
            "purse": 8652541,
            "liquid": 8652541,
            "members": 8,
            "name": "Coconut",
            "gameMode": "Normal",
            "networth": 188337761,
            "unsoulboundNetworth": 188337761,
            "craftedMinions": 682,
            "bonusMinions": 5,
            "levels": "70.22",
            "minionSlots": 31,
        },
        {
            "catacombs": {
                "archer": 0,
                "mage": 0,
                "berserk": 0,
                "tank": 0,
                "healer": 0,
                "level": 0,
            },
            "skills": {
                "Fishing": 0,
                "Mining": 0,
                "Combat": 0,
                "Foraging": 0,
                "Taming": 0,
                "Enchanting": 0,
                "Alchemy": 0,
                "Carpentry": 0,
                "Runecrafting": 0,
                "Social": 0,
                "avg": 0,
            },
            "mining": {"HOTM": 0, "gemstonePowder": 0, "mithrilPowder": 0},
            "slayers": {
                "zombie": 0,
                "spider": 0,
                "wolf": 0,
                "enderman": 0,
                "blaze": 0,
                "vampire": 0,
            },
            "bank": 215007264,
            "purse": 144104,
            "liquid": 215151368,
            "members": 9,
            "name": "Pomegranate",
            "gameMode": "Normal",
            "networth": 215007264,
            "unsoulboundNetworth": 215007264,
            "craftedMinions": 620,
            "bonusMinions": 0,
            "levels": 0,
            "minionSlots": 25,
        },
    ],
    "duels": {
        "wins": 717,
        "losses": 110,
        "kills": 621,
        "deaths": 200,
        "KLRatio": 3.11,
        "title": "Gold III",
        "WLRatio": 6.52,
        "bestWinStreak": 41,
        "currentWinStreak": 6,
    },
    "skywars": {
        "coins": 7722434,
        "winstreak": 0,
        "losses": 16657,
        "wins": 16729,
        "kills": 101814,
        "deaths": 16867,
        "kdr": 6.04,
        "wlr": 1,
        "assists": 5280,
        "levels": 39.0149,
    },
    "bedwars": {
        "coins": 987044,
        "winstreak": 3,
        "losses": 54,
        "wins": 83,
        "finalKills": 358,
        "finalDeaths": 49,
        "fkdr": 7.31,
        "wlr": 1.54,
        "bedsBroken": 216,
        "bedsLost": 70,
        "bblr": 3.09,
        "level": "13.04",
    },
    "rank": "YOUTUBER",
    "name": "refraction",
    "color": "BLACK",
}
