"""Random gamertag generation."""

from __future__ import annotations

import random

_ADJECTIVES = [
    "Swift",
    "Silent",
    "Shadow",
    "Crimson",
    "Frozen",
    "Phantom",
    "Iron",
    "Golden",
    "Dark",
    "Bright",
    "Toxic",
    "Mystic",
    "Neon",
    "Wild",
    "Cursed",
    "Radiant",
    "Savage",
    "Rapid",
    "Ancient",
    "Cosmic",
    "Eternal",
    "Fierce",
    "Haunted",
    "Lethal",
    "Primal",
    "Rogue",
    "Shadow",
    "Stellar",
    "Vicious",
    "Wicked",
    "Blazing",
    "Chaotic",
    "Dread",
    "Eclipse",
    "Feral",
    "Grim",
    "Hollow",
    "Infernal",
    "Jinxed",
    "Knell",
    "Lurking",
    "Manic",
    "Nether",
    "Ominous",
    "Prowling",
    "Quake",
    "Raven",
    "Shade",
    "Twisted",
    "Undead",
]

_NOUNS = [
    "Viper",
    "Wolf",
    "Reaper",
    "Hawk",
    "Tiger",
    "Dragon",
    "Phoenix",
    "Raven",
    "Panther",
    "Cobra",
    "Blade",
    "Storm",
    "Fury",
    "Ghost",
    "Serpent",
    "Spectre",
    "Wraith",
    "Banshee",
    "Striker",
    "Hunter",
    "Demon",
    "Knight",
    "Samurai",
    "Viking",
    "Ronin",
    "Ninja",
    "Spartan",
    "Titan",
    "Golem",
    "Centaur",
    "Minotaur",
    "Hydra",
    "Kraken",
    "Basilisk",
    "Chimera",
    "Griffin",
    "Manticore",
    "Sphinx",
    "Oni",
    "Gargoyle",
    "Revenant",
    "Shade",
    "Warden",
    "Sentinel",
    "Crusader",
    "Paladin",
    "Berserker",
    "Vandal",
    "Pirate",
    "Rogue",
]


def generate_gamertag() -> str:
    """Generate a random gamertag in the format AdjectiveNounNumber.

    Returns:
        A gamertag string like 'SwiftViper42'.
    """
    adjective = random.choice(_ADJECTIVES)
    noun = random.choice(_NOUNS)
    number = random.randint(0, 999)
    return f"{adjective}{noun}{number}"
