"""Language code mappings and fuzzy lookup utilities."""

from __future__ import annotations

from difflib import get_close_matches

LANGUAGES: dict[str, dict[str, str]] = {
    "aa": {"name": "Afar"},
    "ab": {"name": "Abkhazian"},
    "af": {"name": "Afrikaans"},
    "ak": {"name": "Akan"},
    "am": {"name": "Amharic"},
    "ar": {"name": "Arabic"},
    "an": {"name": "Aragonese"},
    "as": {"name": "Assamese"},
    "av": {"name": "Avaric"},
    "ae": {"name": "Avestan"},
    "ay": {"name": "Aymara"},
    "az": {"name": "Azerbaijani"},
    "ba": {"name": "Bashkir"},
    "bm": {"name": "Bambara"},
    "be": {"name": "Belarusian"},
    "bn": {"name": "Bengali"},
    "bi": {"name": "Bislama"},
    "bs": {"name": "Bosnian"},
    "bg": {"name": "Bulgarian"},
    "my": {"name": "Burmese"},
    "ca": {"name": "Catalan"},
    "ch": {"name": "Chamorro"},
    "ce": {"name": "Chechen"},
    "zh": {"name": "Chinese"},
    "cu": {"name": "Church Slavic"},
    "cv": {"name": "Chuvash"},
    "kw": {"name": "Cornish"},
    "co": {"name": "Corsican"},
    "cr": {"name": "Cree"},
    "hr": {"name": "Croatian"},
    "cs": {"name": "Czech"},
    "da": {"name": "Danish"},
    "dv": {"name": "Dhivehi"},
    "nl": {"name": "Dutch"},
    "dz": {"name": "Dzongkha"},
    "en": {"name": "English"},
    "eo": {"name": "Esperanto"},
    "et": {"name": "Estonian"},
    "eu": {"name": "Basque"},
    "ee": {"name": "Ewe"},
    "fo": {"name": "Faroese"},
    "fj": {"name": "Fijian"},
    "fi": {"name": "Finnish"},
    "fr": {"name": "French"},
    "ff": {"name": "Fula"},
    "gd": {"name": "Scottish Gaelic"},
    "gl": {"name": "Galician"},
    "ka": {"name": "Georgian"},
    "de": {"name": "German"},
    "el": {"name": "Greek"},
    "gn": {"name": "Guarani"},
    "gu": {"name": "Gujarati"},
    "ht": {"name": "Haitian Creole"},
    "ha": {"name": "Hausa"},
    "he": {"name": "Hebrew"},
    "hi": {"name": "Hindi"},
    "ho": {"name": "Hiri Motu"},
    "hu": {"name": "Hungarian"},
    "ia": {"name": "Interlingua"},
    "id": {"name": "Indonesian"},
    "ie": {"name": "Interlingue"},
    "ga": {"name": "Irish"},
    "ig": {"name": "Igbo"},
    "ik": {"name": "Inupiaq"},
    "io": {"name": "Ido"},
    "is": {"name": "Icelandic"},
    "it": {"name": "Italian"},
    "iu": {"name": "Inuktitut"},
    "ja": {"name": "Japanese"},
    "jv": {"name": "Javanese"},
    "kn": {"name": "Kannada"},
    "kr": {"name": "Kanuri"},
    "ks": {"name": "Kashmiri"},
    "kk": {"name": "Kazakh"},
    "km": {"name": "Khmer"},
    "ki": {"name": "Kikuyu"},
    "rw": {"name": "Kinyarwanda"},
    "ky": {"name": "Kyrgyz"},
    "kv": {"name": "Komi"},
    "kg": {"name": "Kongo"},
    "ko": {"name": "Korean"},
    "ku": {"name": "Kurdish"},
    "kj": {"name": "Kuanyama"},
    "la": {"name": "Latin"},
    "lb": {"name": "Luxembourgish"},
    "lg": {"name": "Ganda"},
    "li": {"name": "Limburgish"},
    "ln": {"name": "Lingala"},
    "lo": {"name": "Lao"},
    "lt": {"name": "Lithuanian"},
    "lu": {"name": "Luba-Katanga"},
    "lv": {"name": "Latvian"},
    "gv": {"name": "Manx"},
    "mk": {"name": "Macedonian"},
    "mg": {"name": "Malagasy"},
    "ms": {"name": "Malay"},
    "ml": {"name": "Malayalam"},
    "mt": {"name": "Maltese"},
    "mi": {"name": "Maori"},
    "mr": {"name": "Marathi"},
    "mh": {"name": "Marshallese"},
    "mn": {"name": "Mongolian"},
    "na": {"name": "Nauru"},
    "nv": {"name": "Navajo"},
    "nd": {"name": "North Ndebele"},
    "ne": {"name": "Nepali"},
    "ng": {"name": "Ndonga"},
    "nb": {"name": "Norwegian Bokmal"},
    "nn": {"name": "Norwegian Nynorsk"},
    "no": {"name": "Norwegian"},
    "ii": {"name": "Sichuan Yi"},
    "oc": {"name": "Occitan"},
    "oj": {"name": "Ojibwe"},
    "or": {"name": "Odia"},
    "om": {"name": "Oromo"},
    "os": {"name": "Ossetian"},
    "pa": {"name": "Punjabi"},
    "pi": {"name": "Pali"},
    "pl": {"name": "Polish"},
    "pt": {"name": "Portuguese"},
    "ps": {"name": "Pashto"},
    "qu": {"name": "Quechua"},
    "rm": {"name": "Romansh"},
    "ro": {"name": "Romanian"},
    "rn": {"name": "Rundi"},
    "ru": {"name": "Russian"},
    "sg": {"name": "Sango"},
    "sa": {"name": "Sanskrit"},
    "si": {"name": "Sinhala"},
    "sk": {"name": "Slovak"},
    "sl": {"name": "Slovenian"},
    "se": {"name": "Northern Sami"},
    "sm": {"name": "Samoan"},
    "sn": {"name": "Shona"},
    "sd": {"name": "Sindhi"},
    "so": {"name": "Somali"},
    "st": {"name": "Southern Sotho"},
    "es": {"name": "Spanish"},
    "sq": {"name": "Albanian"},
    "sc": {"name": "Sardinian"},
    "sr": {"name": "Serbian"},
    "ss": {"name": "Swati"},
    "su": {"name": "Sundanese"},
    "sw": {"name": "Swahili"},
    "sv": {"name": "Swedish"},
    "ty": {"name": "Tahitian"},
    "ta": {"name": "Tamil"},
    "tt": {"name": "Tatar"},
    "te": {"name": "Telugu"},
    "tg": {"name": "Tajik"},
    "th": {"name": "Thai"},
    "ti": {"name": "Tigrinya"},
    "bo": {"name": "Tibetan"},
    "tk": {"name": "Turkmen"},
    "tl": {"name": "Tagalog"},
    "tn": {"name": "Tswana"},
    "to": {"name": "Tongan"},
    "tr": {"name": "Turkish"},
    "ts": {"name": "Tsonga"},
    "tw": {"name": "Twi"},
    "ug": {"name": "Uyghur"},
    "uk": {"name": "Ukrainian"},
    "ur": {"name": "Urdu"},
    "uz": {"name": "Uzbek"},
    "ve": {"name": "Venda"},
    "vi": {"name": "Vietnamese"},
    "vo": {"name": "Volapuk"},
    "wa": {"name": "Walloon"},
    "cy": {"name": "Welsh"},
    "wo": {"name": "Wolof"},
    "fy": {"name": "Western Frisian"},
    "xh": {"name": "Xhosa"},
    "yi": {"name": "Yiddish"},
    "yo": {"name": "Yoruba"},
    "za": {"name": "Zhuang"},
    "zu": {"name": "Zulu"},
}

_NAME_TO_CODE: dict[str, str] = {}
for code, info in LANGUAGES.items():
    _NAME_TO_CODE[info["name"].lower()] = code
    _NAME_TO_CODE[code.lower()] = code

_ALIASES: dict[str, str] = {
    "english": "en",
    "spanish": "es",
    "french": "fr",
    "german": "de",
    "italian": "it",
    "portuguese": "pt",
    "russian": "ru",
    "japanese": "ja",
    "korean": "ko",
    "chinese": "zh",
    "arabic": "ar",
    "hindi": "hi",
    "dutch": "nl",
    "polish": "pl",
    "turkish": "tr",
    "vietnamese": "vi",
    "thai": "th",
    "swedish": "sv",
    "danish": "da",
    "norwegian": "no",
    "finnish": "fi",
    "greek": "el",
    "czech": "cs",
    "romanian": "ro",
    "hungarian": "hu",
    "ukrainian": "uk",
    "indonesian": "id",
    "malay": "ms",
    "tagalog": "tl",
    "swahili": "sw",
    "hebrew": "he",
    "bengali": "bn",
    "tamil": "ta",
    "urdu": "ur",
    "persian": "fa",
    "farsi": "fa",
}
for alias, code in _ALIASES.items():
    _NAME_TO_CODE[alias] = code


def get_language_code(name: str) -> str | None:
    """Fuzzy-lookup a language name and return its ISO639-1 code.

    Args:
        name: Language name or ISO code.

    Returns:
        The ISO639-1 language code, or None if no match is found.
    """
    key = name.strip().lower()
    if not key:
        return None

    code = _NAME_TO_CODE.get(key)
    if code:
        return code

    all_names = list(_NAME_TO_CODE.keys())
    matches = get_close_matches(key, all_names, n=1, cutoff=0.6)
    if matches:
        return _NAME_TO_CODE[matches[0]]

    return None
