"""Email validation utilities."""

from __future__ import annotations

import re

from autosecure.core.logging import get_logger

log = get_logger("email.validator")

DISPOSABLE_DOMAINS = {
    "guerrillamail.com",
    "tempmail.com",
    "throwaway.email",
    "temp-mail.org",
    "fakeinbox.com",
    "sharklasers.com",
    "guerrillamailblock.com",
    "grr.la",
    "dispostable.com",
    "mailinator.com",
    "yopmail.com",
    "yopmail.fr",
    "guerrillamail.info",
    "guerrillamail.biz",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamail.se",
    "guerrillamail.store",
    "guerrillamail.website",
    "guerrillamail.win",
    "guerrillamail2.com",
    "guerrillamail3.com",
    "guerrillamail4.com",
    "guerrillamail5.com",
    "guerrillamail6.com",
    "guerrillamail7.com",
    "guerrillamail8.com",
    "guerrillamail9.com",
    "harakirimail.com",
    "jetable.org",
    "maildrop.cc",
    "mailnesia.com",
    "mailshell.com",
    "mailsiphon.com",
    "mailslurp.com",
    "mailtechx.com",
    "mailtome.de",
    "mailtothis.com",
    "mailtrash.net",
    "mailzilla.com",
    "mbx.cc",
    "meltmail.com",
    "messagebeamer.de",
    "mohmal.com",
    "nomail.xl.cx",
    "nomail2me.com",
    "nosachamos.org",
    "nowmymail.com",
    "nospam.ze.tc",
    "nospamfor.us",
    "olypmall.com",
    "oneoffemail.com",
    "onewaymail.com",
    "oopi.org",
    "ordinaryamerican.net",
    "otherinbox.com",
    "ourklips.com",
    "outlawonline.net",
    "outpop.com",
    "ovpn.to",
    "owlpic.com",
    "panasas.com",
    "pimpedupmyspace.com",
    "pjjkp.com",
    "plexolan.de",
    "poczta.onet.pl",
    "politikerclub.de",
    "poofy.org",
    "pookmail.com",
    "privacy.net",
    "privatdemail.net",
    "proxymail.eu",
    "prtnx.com",
    "punkass.com",
    "putthisinyouremail.com",
    "qq.com",
    "quickinbox.com",
    "quickmail.nl",
    "rcpt.at",
    "reallymymail.com",
    "realtyalerts.ca",
    "recode.me",
    "recursor.net",
    "regbypass.com",
    "regbypass.comsafe-mail.net",
    "rejectmail.com",
    "reliable-mail.com",
    "rhyta.com",
    "rklips.com",
    "rmqkr.net",
    "royal.net",
    "rppkn.com",
    "rtrtr.com",
    "s0ny.net",
    "safe-mail.net",
    "safersignup.de",
    "safetymail.info",
    "safetypost.de",
    "sandelf.de",
    "saynotospams.com",
    "scatmail.com",
    "schafmail.de",
    "schrott-email.de",
    "secretemail.de",
    "secure-mail.biz",
    "selfdestructingmail.com",
    "sendspam.ca",
    "sharedmailbox.fun",
    "sibmail.com",
    "sinnlos-mail.de",
    "skeefmail.com",
    "slaskpost.se",
    "slipry.net",
    "slopsbox.com",
    "slowslow.de",
    "slutty.horse",
    "smashmail.de",
    "smellfear.com",
    "snakemail.com",
    "sneakemail.com",
    "sneakymail.de",
    "snkmail.com",
    "sofimail.com",
    "sofort-mail.de",
    "sogetthis.com",
    "soodonims.com",
    "spam.la",
    "spam.su",
    "spam4.me",
    "spamavert.com",
    "spambob.com",
    "spambob.net",
    "spambob.org",
    "spambog.com",
    "spambog.de",
    "spambog.ru",
    "spambox.info",
    "spambox.us",
    "spamcannon.com",
    "spamcannon.net",
    "spamcero.com",
    "spamcorptastic.com",
    "spamcowboy.com",
    "spamcowboy.net",
    "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    "spamfighter.cf",
    "spamfighter.ga",
    "spamfighter.gq",
    "spamfighter.ml",
    "spamfighter.tk",
    "spamfree24.com",
    "spamfree24.de",
    "spamfree24.eu",
    "spamfree24.info",
    "spamfree24.net",
    "spamfree24.org",
    "spamgoes.in",
    "spamgourmet.com",
    "spamgourmet.net",
    "spamgourmet.org",
    "spamherelots.com",
    "spamhereplease.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com",
    "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamoff.de",
    "spamslicer.com",
    "spamspot.com",
    "spamstack.net",
    "spamthis.co.uk",
    "spamthisplease.com",
    "spamtrail.com",
    "spamtrap.ro",
    "speed.1s.fr",
    "stuffmail.de",
    "supergreatmail.com",
    "supermailer.jp",
    "superomatic.com",
    "suremail.info",
    "svk.jp",
    "sweetxxx.de",
    "tafmail.com",
    "talkinator.com",
    "tapchicuoihoi.com",
    "teewars.org",
    "teleworm.us",
    "teleworm.com",
    "temp-mail.ru",
    "tempalias.com",
    "tempesta.com",
    "tempemail.biz",
    "tempemail.co.za",
    "tempemail.com",
    "tempemail.net",
    "tempinbox.com",
    "tempinbox.co.uk",
    "tempmail.eu",
    "tempmail.it",
    "tempmail2.com",
    "tempmaildemo.com",
    "tempmailer.com",
    "tempmailer.de",
    "tempomail.fr",
    "temporarily.de",
    "temporarioemail.com.br",
    "temporaryemail.net",
    "temporaryemail.us",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "temporarymailaddress.com",
    "tempthe.net",
    "thankyou2010.com",
    "thc.st",
    "thecloudindex.com",
    "thetempmail.com",
    "throwawayemailaddress.com",
    "tittbit.in",
    "tizi.com",
    "tmailinator.com",
    "toiea.com",
    "toomail.biz",
    "topranklist.de",
    "tradermail.info",
    "trash-amil.com",
    "trash-me.com",
    "trash2009.com",
    "trashdevil.com",
    "trashdevil.de",
    "trashemail.de",
    "trashmail.at",
    "trashmail.com",
    "trashmail.de",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashmail.ws",
    "trashmailer.com",
    "trashmailer.net",
    "trashymail.com",
    "trashymail.net",
    "trillianpro.com",
    "turual.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "umail.net",
    "upliftnow.com",
    "uplipht.com",
    "venompen.com",
    "veryreally.com",
    "viditag.com",
    "viewcastmedia.com",
    "viewcastmedia.net",
    "viewcastmedia.org",
    "vomoto.com",
    "vpn.st",
    "vsimcard.com",
    "vubby.com",
    "wasteland.rfc822.org",
    "webemail.me",
    "weg-werf-email.de",
    "wegwerfadresse.de",
    "wegwerfemail.com",
    "wegwerfemail.de",
    "wegwerfmail.de",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "wetrainbayarea.com",
    "wetrainbayarea.org",
    "wh4f.org",
    "whatiaas.com",
    "whatpaas.com",
    "whyspam.me",
    "wikidocuslice.com",
    "wilemail.com",
    "willhackforfood.biz",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net",
    "wuzupmail.net",
    "wwwnew.eu",
    "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xjoi.com",
    "xmaily.com",
    "xoxy.net",
    "yeag.net",
    "yep.it",
    "yogamaven.com",
    "yomail.info",
    "yopmail.gq",
    "yopmail.net",
    "your-house.net",
    "your-mail.com",
    "yourluckybugs.com",
    "ypmail.webarnak.fr.eu.org",
    "yuurok.com",
    "zehnminutenmail.de",
    "zippymail.info",
    "zoaxe.com",
    "zoemail.org",
}


def validate_email(email: str) -> bool:
    """Validate an email address format.

    Args:
        email: The email address to validate.

    Returns:
        True if the email format is valid.
    """
    pattern = re.compile(
        r"^[a-zA-Z0-9]"
        r"(?:[a-zA-Z0-9._%+-]{0,62}[a-zA-Z0-9])?"
        r"@[a-zA-Z0-9]"
        r"(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?"
        r"(?:\.[a-zA-Z]{2,})+$"
    )
    return bool(pattern.match(email))


def is_disposable(email: str) -> bool:
    """Check if an email uses a disposable email provider.

    Args:
        email: The email address to check.

    Returns:
        True if the email domain is a known disposable provider.
    """
    domain = get_domain(email).lower()
    return domain in DISPOSABLE_DOMAINS


def get_domain(email: str) -> str:
    """Extract the domain from an email address.

    Args:
        email: The email address.

    Returns:
        The domain portion of the email, or empty string if invalid.
    """
    parts = email.split("@")
    if len(parts) == 2:
        return parts[1]
    return ""
